In [1]:
import pandas as pd

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim

In [67]:
import numpy as np

In [3]:
from string import punctuation

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
df = pd.read_csv("d:/git/dados/nlp/news_sentiment_analysis.csv", encoding="utf-8")

In [11]:
df = df.drop(columns=["Source", "Author", "URL", "Published At", "Sentiment"])

In [12]:
df

,Title,Description,Type
0,Pine View High teacher wins Best in State awar...,"ST. GEORGE — Kaitlyn Larson, a first-year teac...",Business
1,Businesses Face Financial Strain Amid Liquidit...,"Harare, Zimbabwe – Local businesses are grappl...",Business
2,Musk donates to super pac working to elect Tru...,(marketscreener.com) Billionaire Elon Musk has...,Business
3,US FTC issues warning to franchisors over unfa...,(marketscreener.com) A U.S. trade regulator on...,Business
4,Rooftop solar's dark side,4.5 million households in the U.S. have solar ...,Business
...,...,...,...
3495,"Arrow Electronics, Inc. (NYSE:ARW) Shares Purc...",QRG Capital Management Inc. increased its stak...,Technology
3496,"3,120 Shares in NICE Ltd. (NASDAQ:NICE) Bought...",QRG Capital Management Inc. bought a new posit...,Technology
3497,"QRG Capital Management Inc. Has $857,000 Stock...",QRG Capital Management Inc. boosted its stake ...,Technology
3498,Biotechnology Market: Surging Investments and ...,"WESTFORD, Mass., July 18, 2024 /PRNewswire/ --...",Technology
3499,"QRG Capital Management Inc. Sells 1,665 Shares...",QRG Capital Management Inc. reduced its holdin...,Technology

In [13]:
print(df["Type"].unique())
print(df["Type"].describe())

['Business' 'Entertainment' 'General' 'Health' 'Science' 'Sports'
 'Technology']
count         3500
unique           7
top       Business
freq           500
Name: Type, dtype: object

In [36]:
# mapping = {'Business': 1, 'Entertainment': 2, 'General': 3, 'Health': 4, 'Science':5, 'Sports':6, 'Technology': 7}
mapping = {
        'Business': [0, 0, 0, 0, 0, 0, 1], 
        'Entertainment': [0, 0, 0, 0, 0, 1, 0],
        'General': [0, 0, 0, 0, 1, 0, 0],
        'Health': [0, 0, 0, 1, 0, 0, 0], 
        'Science': [0, 0, 1, 0, 0, 0, 0],
        'Sports': [0, 1, 0, 0, 0, 0, 0], 
        'Technology': [1, 0, 0, 0, 0, 0, 0]
}
df["type_number"] = df["Type"].map( mapping )

In [37]:
df

,Title,Description,Type,type_number,description_clean
0,Pine View High teacher wins Best in State awar...,"ST. GEORGE — Kaitlyn Larson, a first-year teac...",Business,"[0, 0, 0, 0, 0, 0, 1]",st george — kaitlyn larson a firstyear teacher...
1,Businesses Face Financial Strain Amid Liquidit...,"Harare, Zimbabwe – Local businesses are grappl...",Business,"[0, 0, 0, 0, 0, 0, 1]",harare zimbabwe – local businesses are grappli...
2,Musk donates to super pac working to elect Tru...,(marketscreener.com) Billionaire Elon Musk has...,Business,"[0, 0, 0, 0, 0, 0, 1]",marketscreenercom billionaire elon musk has do...
3,US FTC issues warning to franchisors over unfa...,(marketscreener.com) A U.S. trade regulator on...,Business,"[0, 0, 0, 0, 0, 0, 1]",marketscreenercom a us trade regulator on frid...
4,Rooftop solar's dark side,4.5 million households in the U.S. have solar ...,Business,"[0, 0, 0, 0, 0, 0, 1]",45 million households in the us have solar pan...
...,...,...,...,...,...
3495,"Arrow Electronics, Inc. (NYSE:ARW) Shares Purc...",QRG Capital Management Inc. increased its stak...,Technology,"[1, 0, 0, 0, 0, 0, 0]",qrg capital management inc increased its stake...
3496,"3,120 Shares in NICE Ltd. (NASDAQ:NICE) Bought...",QRG Capital Management Inc. bought a new posit...,Technology,"[1, 0, 0, 0, 0, 0, 0]",qrg capital management inc bought a new positi...
3497,"QRG Capital Management Inc. Has $857,000 Stock...",QRG Capital Management Inc. boosted its stake ...,Technology,"[1, 0, 0, 0, 0, 0, 0]",qrg capital management inc boosted its stake i...
3498,Biotechnology Market: Surging Investments and ...,"WESTFORD, Mass., July 18, 2024 /PRNewswire/ --...",Technology,"[1, 0, 0, 0, 0, 0, 0]",westford mass july 18 2024 prnewswire accordi...
3499,"QRG Capital Management Inc. Sells 1,665 Shares...",QRG Capital Management Inc. reduced its holdin...,Technology,"[1, 0, 0, 0, 0, 0, 0]",qrg capital management inc reduced its holding...

In [38]:
Y = torch.tensor(df["type_number"], dtype=torch.float32)
Y = torch.reshape(Y, (-1, 7))

In [39]:
Y.shape

torch.Size([3500, 7])

In [40]:
table = str.maketrans("", "", punctuation)

def limpar( texto ):
    texto_limpo = texto.lower().translate(table)
    return texto_limpo

In [41]:
df["description_clean"] = df["Description"].apply(limpar)

In [82]:
indice_analisar = 843

In [83]:
df["Type"][indice_analisar]

'Entertainment'

In [84]:
df["description_clean"][indice_analisar]

'ap entertainment writer new york ap — richard simmons television8217s hyperactive court jester of physical fitness who built a miniempire in his trademark tank tops and short shorts by urging the overweight to exercise and eat better died saturday he turned 76 on friday los angeles police and fire departments say they responded to athe post richard simmons a fitness guru who mixed laughs and sweat dies at 76 appeared first on kvia'

In [ ]:
[
    ["o", "rato", "roeu", "a", "roupa", "do", "rei"],
    ["o", "rei", "ria", "sem", "parar"]
]

In [ ]:
{
    "o": 1,
    "rato": 2,
    "roeu": 3,
    "a": 4,
    "roupa": 5,
    "do": 6,
    "rei": 7,
    "ria": 8,
    "sem": 9,
    "parar": 10
}

In [ ]:
## Vetorização com base em numero do token
[
    [1, 2, 3, 4, 5, 6, 7],
    [1, 7, 8, 9, 10]
]

In [ ]:
## Vetorização com base em Bag of Words
## Indice : 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
[
    [ 1, 1, 1, 1, 1, 1, 1, 0, 0, 0 ],
    [ 1, 0, 0, 0, 0, 0, 1, 1, 1, 1 ]
]

In [43]:
vetorizador = CountVectorizer(max_features=1000)

In [44]:
texto_vetorizado = vetorizador.fit_transform(df["description_clean"])

In [45]:
dicionario = vetorizador.get_feature_names_out()
dicionario

array(['07', '10', '100', '11', '12', '13', '13f', '14', '141st', '15',
       '15th', '16', '17', '18', '18th', '1st', '20', '2020', '2022',
       '2023', '2024', '202425', '2025', '21', '24', '25', '26', '30',
       '40', '8211', '8212', '8230', '8230the', '90', '92nd', 'about',
       'access', 'accesswire', 'according', 'acquired', 'acquiring',
       'across', 'act', 'action', 'activities', 'ad', 'added',
       'additional', 'address', 'administration', 'advanced', 'advisors',
       'advisory', 'afb', 'africa', 'after', 'against', 'agency', 'ago',
       'agreement', 'ahead', 'ai', 'air', 'aircraft', 'airman', 'aktie',
       'al', 'all', 'alla', 'allstar', 'als', 'also', 'amazon', 'america',
       'american', 'americas', 'amid', 'among', 'an', 'analyse',
       'analyst', 'analysts', 'and', 'angeles', 'announce', 'announced',
       'announces', 'announcing', 'annual', 'another', 'any', 'ap', 'app',
       'appeared', 'applications', 'approximately', 'are', 'area',
       'arlington', 'army', 'around', 'art', 'article', 'artificial',
       'arts', 'arw', 'as', 'asphalt', 'assassinate', 'assigned', 'assn',
       'associated', 'at', 'attention', 'attorney', 'auch', 'auf',
       'august', 'australian', 'available', 'avantax', 'average', 'award',
       'away', 'awful', 'back', 'bank', 'base', 'based', 'bases', 'be',
       'because', 'become', 'been', 'before', 'begin', 'bei', 'being',
       'best', 'beta', 'better', 'between', 'biden', 'big', 'bill',
       'billion', 'board', 'boosted', 'both', 'bought', 'brand',
       'brigade', 'british', 'brown', 'business', 'businesses', 'busy',
       'but', 'buy', 'buying', 'by', 'calif', 'california', 'call',
       'called', 'campaign', 'can', 'canada', 'canadian', 'capabilities',
       'capability', 'capital', 'care', 'career', 'cash', 'center',
       'centers', 'central', 'centre', 'century', 'ceo', 'ceremony',
       'challenges', 'change', 'changed', 'changes', 'channel', 'che',
       'chicago', 'chief', 'children', 'chris', 'city', 'civil', 'class',
       'clear', 'close', 'closed', 'club', 'co', 'coach', 'col',
       'collaboration', 'college', 'colleges', 'colorado', 'combat',
       'come', 'comes', 'coming', 'command', 'commander', 'commands',
       'commission', 'common', 'communication', 'community', 'companies',
       'company', 'company8217s', 'competition', 'complete', 'complex',
       'con', 'concerns', 'conducted', 'conference', 'construction',
       'content', 'continue', 'continues', 'contract', 'control',
       'convincing', 'copa', 'corp', 'corporation', 'corps', 'corus',
       'could', 'council', 'country', 'county', 'court', 'crew',
       'critical', 'crucial', 'cup', 'currently', 'cut', 'da', 'daily',
       'das', 'data', 'day', 'days', 'de', 'deal', 'declared', 'decline',
       'defense', 'dei', 'del', 'della', 'dem', 'den', 'department',
       'der', 'des', 'development', 'di', 'die', 'died', 'digital',
       'director', 'directors', 'disclosure', 'disease', 'dividend',
       'division', 'do', 'donald', 'donegal', 'doubled', 'down', 'dr',
       'draft', 'du', 'due', 'during', 'ea', 'each', 'eagles', 'earlier',
       'early', 'earnings', 'economic', 'education', 'ein', 'eine',
       'einer', 'el', 'election', 'em', 'emergency', 'empirical', 'en',
       'enable', 'end', 'energy', 'engineer', 'engineering', 'england',
       'entertaining', 'entertainment', 'environmental', 'equity', 'era',
       'erdc', 'es', 'espn', 'essentiallysports', 'est', 'este', 'et',
       'etf', 'euro', 'european', 'evaluation', 'even', 'event', 'events',
       'ever', 'every', 'exchange', 'executive', 'expected', 'experience',
       'experts', 'face', 'facility', 'fair', 'fairchild', 'family',
       'fans', 'fbi', 'fc', 'federal', 'fest', 'few', 'field', 'filed',
       'filing', 'film', 'final', 'financial', 'firm', 'first',
       'firstyear', 'fitness', 'five', 'flight', 'focus', 'focuses',
       'following', 'food', 'football', 'for', 'force', 'forces', 'form',
       'former', 'fort', 'four', 'france', 'free', 'friday', 'from',
       'full', 'fund', 'funds', 'further', 'future', 'für', 'game',
       'games', 'garland', 'gathers', 'gaza', 'gen', 'gender', 'general',
       'generale', 'generate', 'generation', 'get', 'given', 'global',
       'go', 'going', 'good', 'government', 'grant', 'great', 'grew',
       'group', 'growth', 'guidance', 'ha', 'had', 'half', 'hall', 'has',
       'hat', 'have', 'he', 'head', 'headlands', 'health', 'healthcare',
       'heat', 'hedge', 'held', 'help', 'her', 'here', 'high', 'him',
       'hines', 'his', 'history', 'hold', 'holdings', 'holistic', 'home',
       'homes', 'hospital', 'hospitals', 'host', 'hosted', 'hot', 'house',
       'houston', 'how', 'human', 'identifying', 'if', 'il', 'im',
       'image', 'in', 'inc', 'included', 'including', 'increase',
       'increased', 'index', 'india', 'industrial', 'industry',
       'information', 'innovation', 'innovative', 'inside', 'inspection',
       'inspector', 'institute', 'institutional', 'insurance',
       'intelligence', 'interest', 'international', 'interview', 'into',
       'investment', 'investments', 'investor', 'investors', 'iot', 'is',
       'israeli', 'issued', 'issues', 'ist', 'it', 'its', 'james', 'jean',
       'joe', 'john', 'joint', 'journal', 'jr', 'judge', 'julio', 'july',
       'june', 'just', 'keep', 'key', 'killed', 'know', 'known', 'la',
       'laboratory', 'large', 'largest', 'larry', 'larticolo', 'las',
       'last', 'latest', 'launched', 'law', 'le', 'lead', 'leader',
       'leading', 'league', 'least', 'led', 'left', 'legal', 'leggi',
       'les', 'letzten', 'level', 'liberty', 'life', 'like', 'limited',
       'line', 'little', 'live', 'llc', 'llc8217s', 'llp', 'local',
       'london', 'long', 'look', 'los', 'lp', 'ltd', 'luglio', 'made',
       'main', 'maj', 'major', 'make', 'making', 'man', 'management',
       'manager', 'many', 'marine', 'market', 'markets',
       'marketscreenercom', 'mass', 'massive', 'may', 'media', 'medical',
       'meeting', 'mehr', 'members', 'mental', 'merrick', 'met',
       'michael', 'might', 'military', 'million', 'minister', 'ministry',
       'mission', 'mit', 'mlb', 'mobile', 'mobility', 'monday', 'month',
       'months', 'moore', 'more', 'morethe', 'most', 'move', 'moving',
       'much', 'music', 'must', 'my', 'name', 'nation', 'national',
       'navy', 'nbc', 'nc', 'near', 'need', 'needs', 'nel', 'network',
       'new', 'news', 'next', 'nfl', 'nigeria', 'night', 'nintendo', 'no',
       'non', 'nonconforming', 'nonotice', 'nori', 'north', 'not', 'note',
       'notification', 'now', 'nuclear', 'number', 'nuovo', 'of', 'off',
       'office', 'officer', 'official', 'officials', 'olympic',
       'olympics', 'on', 'one', 'online', 'only', 'ontario', 'open',
       'opened', 'opening', 'operational', 'operations', 'oppenheimer',
       'opportunities', 'opportunity', 'or', 'order', 'organizations',
       'other', 'our', 'out', 'over', 'overall', 'own', 'owned', 'owners',
       'ownership', 'pandemic', 'para', 'parents', 'paris', 'park',
       'part', 'partners', 'party', 'passed', 'past', 'patients', 'pay',
       'penn', 'people', 'per', 'percentage', 'perform', 'performance',
       'period', 'persuasion', 'phone', 'photo', 'photos', 'physical',
       'più', 'place', 'plan', 'play', 'played', 'players', 'plc',
       'police', 'politician', 'politics', 'por', 'position', 'positive',
       'post', 'potential', 'pour', 'power', 'premier', 'president',
       'presidential', 'press', 'prevention', 'previously', 'price',
       'prime', 'prior', 'private', 'prnewswire', 'products',
       'profitability', 'program', 'project', 'provide', 'provider8217s',
       'provides', 'providing', 'prozent', 'public', 'published',
       'purchased', 'purchasing', 'qrg', 'quality', 'quarter',
       'quarterly', 'que', 'radio', 'raised', 'rally', 'rate', 'rating',
       're', 'read', 'readiness', 'received', 'recent', 'recently',
       'recommendations', 'record', 'red', 'refueling', 'release',
       'released', 'report', 'reported', 'reports', 'republican',
       'research', 'researchers', 'resources', 'results', 'return',
       'revenue', 'right', 'rights', 'risk', 'road', 'robert', 'role',
       'rsi', 'russell', 'safety', 'said', 'sale', 'sales', 'same',
       'sameday', 'san', 'santa', 'saturday', 'say', 'says', 'school',
       'science', 'sciences', 'se', 'season', 'sec', 'second', 'sector',
       'securities', 'security', 'see', 'seen', 'selling', 'senior',
       'september', 'series', 'service', 'services', 'set', 'several',
       'sg', 'sgt', 'share', 'shareholders', 'shares', 'she', 'short',
       'show', 'shows', 'si', 'sich', 'side', 'sie', 'signed',
       'significant', 'since', 'sind', 'site', 'size', 'skills', 'small',
       'so', 'social', 'software', 'sold', 'soldier', 'soldiers',
       'solutions', 'some', 'son', 'sono', 'south', 'sox', 'space',
       'spain', 'special', 'sport', 'sporting', 'sports', 'squadron',
       'st', 'staff', 'stake', 'star', 'start', 'state', 'states',
       'steam', 'stem', 'still', 'stock', 'stocks', 'streaming', 'street',
       'strength', 'structures', 'students', 'study', 'su', 'such',
       'summer', 'sunday', 'super', 'support', 'sur', 'surveys', 'switch',
       'symptoms', 'system', 'systems', 'take', 'takes', 'taking',
       'talent', 'talk', 'target', 'taylor', 'team', 'teams', 'tech',
       'technical', 'technologies', 'technology', 'television', 'tell',
       'tennis', 'test', 'texas', 'than', 'that', 'the', 'their', 'them',
       'there', 'these', 'they', 'things', 'third', 'this', 'those',
       'three', 'through', 'throughout', 'thursday', 'time', 'times',
       'title', 'to', 'today', 'took', 'top', 'toronto', 'total', 'tour',
       'trade', 'traded', 'trading', 'training', 'transaction',
       'transgender', 'treatment', 'tribune', 'tried', 'trump', 'trust',
       'tuesday', 'tv', 'two', 'um', 'un', 'una', 'und', 'under', 'unit',
       'united', 'units', 'university', 'up', 'update', 'us', 'usa',
       'use', 'used', 'using', 'value', 'valued', 'various', 'via',
       'video', 'virginia', 'volume', 'von', 'vs', 'wall', 'want', 'was',
       'washington', 'watch', 'water', 'way', 'we', 'webb', 'wednesday',
       'week', 'weekend', 'weeks', 'well', 'wellness', 'were', 'west',
       'what', 'when', 'where', 'which', 'while', 'white', 'whiteman',
       'who', 'why', 'wide', 'wie', 'will', 'wing', 'with', 'without',
       'woman', 'women', 'won', 'work', 'working', 'works', 'world',
       'worth', 'would', 'wray', 'writer', 'wwe', 'year', 'yearly',
       'years', 'york', 'you', 'your', 'yourself', 'zu', 'über'],
      dtype=object)

In [29]:
# texto_vetorizado.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(3500, 1000))

In [46]:
X = torch.tensor(texto_vetorizado.toarray(), dtype=torch.float32)
X

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [47]:
print("X: ", X.dtype, X.shape, X.ndim)
print("Y: ", Y.dtype, Y.shape, Y.ndim)

X:  torch.float32 torch.Size([3500, 1000]) 2
Y:  torch.float32 torch.Size([3500, 7]) 2

In [48]:
modelo = nn.Linear(in_features = 1000, out_features=7)

In [49]:
criterio = nn.CrossEntropyLoss() # Cross Entropy
otimizador = optim.SGD( modelo.parameters(), lr=0.01 )

In [50]:
for epoca in range(1, 3001):
    Y_hat = modelo( X )
    loss = criterio( Y_hat, Y )
    otimizador.zero_grad()
    loss.backward()
    otimizador.step()
    print(f"Epoca: {epoca}\tLoss:{loss}")

Epoca: 1	Loss:1.947597622871399
Epoca: 2	Loss:1.9451555013656616
Epoca: 3	Loss:1.9427380561828613
Epoca: 4	Loss:1.9403454065322876
Epoca: 5	Loss:1.937976598739624
Epoca: 6	Loss:1.9356310367584229
Epoca: 7	Loss:1.9333078861236572
Epoca: 8	Loss:1.9310067892074585
Epoca: 9	Loss:1.9287272691726685
Epoca: 10	Loss:1.9264684915542603
Epoca: 11	Loss:1.9242298603057861
Epoca: 12	Loss:1.9220107793807983
Epoca: 13	Loss:1.9198111295700073
Epoca: 14	Loss:1.9176297187805176
Epoca: 15	Loss:1.9154666662216187
Epoca: 16	Loss:1.9133211374282837
Epoca: 17	Loss:1.9111931324005127
Epoca: 18	Loss:1.9090813398361206
Epoca: 19	Loss:1.9069859981536865
Epoca: 20	Loss:1.9049067497253418
Epoca: 21	Loss:1.90284264087677
Epoca: 22	Loss:1.9007935523986816
Epoca: 23	Loss:1.8987592458724976
Epoca: 24	Loss:1.89673912525177
Epoca: 25	Loss:1.8947327136993408
Epoca: 26	Loss:1.89274001121521
Epoca: 27	Loss:1.8907606601715088
Epoca: 28	Loss:1.8887940645217896
Epoca: 29	Loss:1.8868399858474731
Epoca: 30	Loss:1.8848981857299805
Epoca: 31	Loss:1.8829683065414429
Epoca: 32	Loss:1.8810502290725708
Epoca: 33	Loss:1.879143238067627
Epoca: 34	Loss:1.8772474527359009
Epoca: 35	Loss:1.8753629922866821
Epoca: 36	Loss:1.8734887838363647
Epoca: 37	Loss:1.8716251850128174
Epoca: 38	Loss:1.8697712421417236
Epoca: 39	Loss:1.8679275512695312
Epoca: 40	Loss:1.8660937547683716
Epoca: 41	Loss:1.8642691373825073
Epoca: 42	Loss:1.8624539375305176
Epoca: 43	Loss:1.8606479167938232
Epoca: 44	Loss:1.8588508367538452
Epoca: 45	Loss:1.8570624589920044
Epoca: 46	Loss:1.8552826642990112
Epoca: 47	Loss:1.8535113334655762
Epoca: 48	Loss:1.8517482280731201
Epoca: 49	Loss:1.849993109703064
Epoca: 50	Loss:1.8482462167739868
Epoca: 51	Loss:1.846506953239441
Epoca: 52	Loss:1.8447751998901367
Epoca: 53	Loss:1.8430511951446533
Epoca: 54	Loss:1.8413348197937012
Epoca: 55	Loss:1.8396252393722534
Epoca: 56	Loss:1.8379230499267578
Epoca: 57	Loss:1.8362280130386353
Epoca: 58	Loss:1.8345396518707275
Epoca: 59	Loss:1.8328582048416138
Epoca: 60	Loss:1.8311837911605835
Epoca: 61	Loss:1.8295155763626099
Epoca: 62	Loss:1.8278539180755615
Epoca: 63	Loss:1.826198935508728
Epoca: 64	Loss:1.8245500326156616
Epoca: 65	Loss:1.8229076862335205
Epoca: 66	Loss:1.8212711811065674
Epoca: 67	Loss:1.8196407556533813
Epoca: 68	Loss:1.8180164098739624
Epoca: 69	Loss:1.8163981437683105
Epoca: 70	Loss:1.8147855997085571
Epoca: 71	Loss:1.8131788969039917
Epoca: 72	Loss:1.8115776777267456
Epoca: 73	Loss:1.809982180595398
Epoca: 74	Loss:1.8083921670913696
Epoca: 75	Loss:1.8068079948425293
Epoca: 76	Loss:1.8052289485931396
Epoca: 77	Loss:1.8036553859710693
Epoca: 78	Loss:1.8020870685577393
Epoca: 79	Loss:1.800524115562439
Epoca: 80	Loss:1.7989662885665894
Epoca: 81	Loss:1.7974133491516113
Epoca: 82	Loss:1.7958658933639526
Epoca: 83	Loss:1.794323205947876
Epoca: 84	Loss:1.7927857637405396
Epoca: 85	Loss:1.7912530899047852
Epoca: 86	Loss:1.7897253036499023
Epoca: 87	Loss:1.7882022857666016
Epoca: 88	Loss:1.7866840362548828
Epoca: 89	Loss:1.7851706743240356
Epoca: 90	Loss:1.783661961555481
Epoca: 91	Loss:1.7821578979492188
Epoca: 92	Loss:1.780658483505249
Epoca: 93	Loss:1.7791634798049927
Epoca: 94	Loss:1.7776731252670288
Epoca: 95	Loss:1.7761874198913574
Epoca: 96	Loss:1.7747058868408203
Epoca: 97	Loss:1.7732291221618652
Epoca: 98	Loss:1.7717564105987549
Epoca: 99	Loss:1.7702882289886475
Epoca: 100	Loss:1.7688242197036743
Epoca: 101	Loss:1.767364501953125
Epoca: 102	Loss:1.7659090757369995
Epoca: 103	Loss:1.7644580602645874
Epoca: 104	Loss:1.7630106210708618
Epoca: 105	Loss:1.7615678310394287
Epoca: 106	Loss:1.7601287364959717
Epoca: 107	Loss:1.758694052696228
Epoca: 108	Loss:1.7572633028030396
Epoca: 109	Loss:1.7558363676071167
Epoca: 110	Loss:1.7544136047363281
Epoca: 111	Loss:1.7529950141906738
Epoca: 112	Loss:1.751579761505127
Epoca: 113	Loss:1.750168800354004
Epoca: 114	Loss:1.748761534690857
Epoca: 115	Loss:1.747357964515686
Epoca: 116	Loss:1.745958685874939
Epoca: 117	Loss:1.7445627450942993
Epoca: 118	Loss:1.7431706190109253
Epoca: 119	Loss:1.741782307624817
Epoca: 120	Loss:1.740397572517395
Epoca: 121	Loss:1.7390166521072388
Epoca: 122	Loss:1.7376391887664795
Epoca: 123	Loss:1.7362656593322754
Epoca: 124	Loss:1.7348953485488892
Epoca: 125	Loss:1.733528971672058
Epoca: 126	Loss:1.7321656942367554
Epoca: 127	Loss:1.7308063507080078
Epoca: 128	Loss:1.7294503450393677
Epoca: 129	Loss:1.728097677230835
Epoca: 130	Loss:1.7267485857009888
Epoca: 131	Loss:1.7254027128219604
Epoca: 132	Loss:1.7240605354309082
Epoca: 133	Loss:1.7227216958999634
Epoca: 134	Loss:1.721386194229126
Epoca: 135	Loss:1.720054030418396
Epoca: 136	Loss:1.7187248468399048
Epoca: 137	Loss:1.7173993587493896
Epoca: 138	Loss:1.7160769701004028
Epoca: 139	Loss:1.714758038520813
Epoca: 140	Loss:1.7134422063827515
Epoca: 141	Loss:1.7121294736862183
Epoca: 142	Loss:1.710820198059082
Epoca: 143	Loss:1.709513783454895
Epoca: 144	Loss:1.708210825920105
Epoca: 145	Loss:1.7069108486175537
Epoca: 146	Loss:1.7056139707565308
Epoca: 147	Loss:1.7043200731277466
Epoca: 148	Loss:1.7030292749404907
Epoca: 149	Loss:1.7017418146133423
Epoca: 150	Loss:1.700457215309143
Epoca: 151	Loss:1.6991753578186035
Epoca: 152	Loss:1.6978967189788818
Epoca: 153	Loss:1.6966214179992676
Epoca: 154	Loss:1.6953486204147339
Epoca: 155	Loss:1.6940791606903076
Epoca: 156	Loss:1.6928123235702515
Epoca: 157	Loss:1.691548228263855
Epoca: 158	Loss:1.690287709236145
Epoca: 159	Loss:1.6890296936035156
Epoca: 160	Loss:1.6877745389938354
Epoca: 161	Loss:1.6865220069885254
Epoca: 162	Loss:1.6852725744247437
Epoca: 163	Loss:1.6840260028839111
Epoca: 164	Loss:1.6827820539474487
Epoca: 165	Loss:1.6815409660339355
Epoca: 166	Loss:1.6803027391433716
Epoca: 167	Loss:1.6790671348571777
Epoca: 168	Loss:1.677834391593933
Epoca: 169	Loss:1.6766043901443481
Epoca: 170	Loss:1.6753770112991333
Epoca: 171	Loss:1.6741523742675781
Epoca: 172	Loss:1.672930359840393
Epoca: 173	Loss:1.6717110872268677
Epoca: 174	Loss:1.6704944372177124
Epoca: 175	Loss:1.6692804098129272
Epoca: 176	Loss:1.6680690050125122
Epoca: 177	Loss:1.6668602228164673
Epoca: 178	Loss:1.665654182434082
Epoca: 179	Loss:1.6644506454467773
Epoca: 180	Loss:1.6632494926452637
Epoca: 181	Loss:1.6620512008666992
Epoca: 182	Loss:1.6608554124832153
Epoca: 183	Loss:1.6596620082855225
Epoca: 184	Loss:1.6584712266921997
Epoca: 185	Loss:1.6572829484939575
Epoca: 186	Loss:1.6560970544815063
Epoca: 187	Loss:1.6549137830734253
Epoca: 188	Loss:1.6537328958511353
Epoca: 189	Loss:1.6525543928146362
Epoca: 190	Loss:1.6513785123825073
Epoca: 191	Loss:1.6502047777175903
Epoca: 192	Loss:1.6490339040756226
Epoca: 193	Loss:1.6478650569915771
Epoca: 194	Loss:1.6466989517211914
Epoca: 195	Loss:1.6455349922180176
Epoca: 196	Loss:1.6443732976913452
Epoca: 197	Loss:1.6432143449783325
Epoca: 198	Loss:1.6420574188232422
Epoca: 199	Loss:1.6409028768539429
Epoca: 200	Loss:1.6397508382797241
Epoca: 201	Loss:1.6386011838912964
Epoca: 202	Loss:1.6374536752700806
Epoca: 203	Loss:1.6363083124160767
Epoca: 204	Loss:1.6351653337478638
Epoca: 205	Loss:1.6340248584747314
Epoca: 206	Loss:1.6328864097595215
Epoca: 207	Loss:1.631750226020813
Epoca: 208	Loss:1.6306166648864746
Epoca: 209	Loss:1.62948477268219
Epoca: 210	Loss:1.6283555030822754
Epoca: 211	Loss:1.6272282600402832
Epoca: 212	Loss:1.6261032819747925
Epoca: 213	Loss:1.6249805688858032
Epoca: 214	Loss:1.6238598823547363
Epoca: 215	Loss:1.6227415800094604
Epoca: 216	Loss:1.6216251850128174
Epoca: 217	Loss:1.6205111742019653
Epoca: 218	Loss:1.6193994283676147
Epoca: 219	Loss:1.618289589881897
Epoca: 220	Loss:1.6171817779541016
Epoca: 221	Loss:1.6160764694213867
Epoca: 222	Loss:1.6149729490280151
Epoca: 223	Loss:1.613871455192566
Epoca: 224	Loss:1.6127724647521973
Epoca: 225	Loss:1.6116752624511719
Epoca: 226	Loss:1.6105802059173584
Epoca: 227	Loss:1.6094872951507568
Epoca: 228	Loss:1.6083961725234985
Epoca: 229	Loss:1.6073073148727417
Epoca: 230	Loss:1.6062207221984863
Epoca: 231	Loss:1.6051357984542847
Epoca: 232	Loss:1.6040529012680054
Epoca: 233	Loss:1.602972149848938
Epoca: 234	Loss:1.601893424987793
Epoca: 235	Loss:1.6008167266845703
Epoca: 236	Loss:1.59974205493927
Epoca: 237	Loss:1.598669171333313
Epoca: 238	Loss:1.5975983142852783
Epoca: 239	Loss:1.596529483795166
Epoca: 240	Loss:1.5954625606536865
Epoca: 241	Loss:1.5943979024887085
Epoca: 242	Loss:1.5933347940444946
Epoca: 243	Loss:1.5922737121582031
Epoca: 244	Loss:1.591214656829834
Epoca: 245	Loss:1.590157389640808
Epoca: 246	Loss:1.5891021490097046
Epoca: 247	Loss:1.5880489349365234
Epoca: 248	Loss:1.586997389793396
Epoca: 249	Loss:1.585947871208191
Epoca: 250	Loss:1.5849002599716187
Epoca: 251	Loss:1.5838543176651
Epoca: 252	Loss:1.5828105211257935
Epoca: 253	Loss:1.58176851272583
Epoca: 254	Loss:1.58072829246521
Epoca: 255	Loss:1.5796897411346436
Epoca: 256	Loss:1.5786534547805786
Epoca: 257	Loss:1.5776187181472778
Epoca: 258	Loss:1.5765858888626099
Epoca: 259	Loss:1.5755549669265747
Epoca: 260	Loss:1.5745257139205933
Epoca: 261	Loss:1.5734981298446655
Epoca: 262	Loss:1.5724728107452393
Epoca: 263	Loss:1.5714490413665771
Epoca: 264	Loss:1.5704271793365479
Epoca: 265	Loss:1.5694068670272827
Epoca: 266	Loss:1.5683883428573608
Epoca: 267	Loss:1.5673716068267822
Epoca: 268	Loss:1.566356897354126
Epoca: 269	Loss:1.5653437376022339
Epoca: 270	Loss:1.564332365989685
Epoca: 271	Loss:1.56332266330719
Epoca: 272	Loss:1.5623148679733276
Epoca: 273	Loss:1.5613086223602295
Epoca: 274	Loss:1.5603042840957642
Epoca: 275	Loss:1.559301495552063
Epoca: 276	Loss:1.5583006143569946
Epoca: 277	Loss:1.5573012828826904
Epoca: 278	Loss:1.55630362033844
Epoca: 279	Loss:1.5553078651428223
Epoca: 280	Loss:1.5543136596679688
Epoca: 281	Loss:1.5533210039138794
Epoca: 282	Loss:1.5523303747177124
Epoca: 283	Loss:1.5513410568237305
Epoca: 284	Loss:1.5503536462783813
Epoca: 285	Loss:1.5493677854537964
Epoca: 286	Loss:1.5483838319778442
Epoca: 287	Loss:1.5474010705947876
Epoca: 288	Loss:1.5464202165603638
Epoca: 289	Loss:1.5454411506652832
Epoca: 290	Loss:1.5444636344909668
Epoca: 291	Loss:1.543487548828125
Epoca: 292	Loss:1.542513370513916
Epoca: 293	Loss:1.5415406227111816
Epoca: 294	Loss:1.5405696630477905
Epoca: 295	Loss:1.539600133895874
Epoca: 296	Loss:1.5386322736740112
Epoca: 297	Loss:1.5376657247543335
Epoca: 298	Loss:1.5367013216018677
Epoca: 299	Loss:1.5357379913330078
Epoca: 300	Loss:1.5347766876220703
Epoca: 301	Loss:1.5338166952133179
Epoca: 302	Loss:1.5328583717346191
Epoca: 303	Loss:1.5319015979766846
Epoca: 304	Loss:1.5309463739395142
Epoca: 305	Loss:1.529992699623108
Epoca: 306	Loss:1.5290406942367554
Epoca: 307	Loss:1.5280901193618774
Epoca: 308	Loss:1.5271410942077637
Epoca: 309	Loss:1.526193618774414
Epoca: 310	Loss:1.5252478122711182
Epoca: 311	Loss:1.5243033170700073
Epoca: 312	Loss:1.5233603715896606
Epoca: 313	Loss:1.5224190950393677
Epoca: 314	Loss:1.5214791297912598
Epoca: 315	Loss:1.5205408334732056
Epoca: 316	Loss:1.5196040868759155
Epoca: 317	Loss:1.5186687707901
Epoca: 318	Loss:1.5177351236343384
Epoca: 319	Loss:1.5168027877807617
Epoca: 320	Loss:1.5158717632293701
Epoca: 321	Loss:1.5149425268173218
Epoca: 322	Loss:1.5140146017074585
Epoca: 323	Loss:1.5130882263183594
Epoca: 324	Loss:1.5121632814407349
Epoca: 325	Loss:1.5112396478652954
Epoca: 326	Loss:1.5103178024291992
Epoca: 327	Loss:1.509397268295288
Epoca: 328	Loss:1.508478045463562
Epoca: 329	Loss:1.5075604915618896
Epoca: 330	Loss:1.5066442489624023
Epoca: 331	Loss:1.5057296752929688
Epoca: 332	Loss:1.5048162937164307
Epoca: 333	Loss:1.5039044618606567
Epoca: 334	Loss:1.5029940605163574
Epoca: 335	Loss:1.5020849704742432
Epoca: 336	Loss:1.501177191734314
Epoca: 337	Loss:1.5002710819244385
Epoca: 338	Loss:1.4993664026260376
Epoca: 339	Loss:1.4984629154205322
Epoca: 340	Loss:1.497560977935791
Epoca: 341	Loss:1.4966604709625244
Epoca: 342	Loss:1.4957611560821533
Epoca: 343	Loss:1.4948633909225464
Epoca: 344	Loss:1.4939671754837036
Epoca: 345	Loss:1.4930720329284668
Epoca: 346	Loss:1.4921785593032837
Epoca: 347	Loss:1.4912861585617065
Epoca: 348	Loss:1.490395188331604
Epoca: 349	Loss:1.4895057678222656
Epoca: 350	Loss:1.4886177778244019
Epoca: 351	Loss:1.487730860710144
Epoca: 352	Loss:1.4868453741073608
Epoca: 353	Loss:1.4859613180160522
Epoca: 354	Loss:1.4850786924362183
Epoca: 355	Loss:1.4841972589492798
Epoca: 356	Loss:1.483317255973816
Epoca: 357	Loss:1.482438564300537
Epoca: 358	Loss:1.481561303138733
Epoca: 359	Loss:1.4806852340698242
Epoca: 360	Loss:1.479810357093811
Epoca: 361	Loss:1.478937029838562
Epoca: 362	Loss:1.478065013885498
Epoca: 363	Loss:1.4771943092346191
Epoca: 364	Loss:1.4763249158859253
Epoca: 365	Loss:1.475456714630127
Epoca: 366	Loss:1.4745901823043823
Epoca: 367	Loss:1.4737244844436646
Epoca: 368	Loss:1.4728602170944214
Epoca: 369	Loss:1.4719973802566528
Epoca: 370	Loss:1.4711357355117798
Epoca: 371	Loss:1.4702755212783813
Epoca: 372	Loss:1.4694162607192993
Epoca: 373	Loss:1.4685587882995605
Epoca: 374	Loss:1.4677021503448486
Epoca: 375	Loss:1.4668470621109009
Epoca: 376	Loss:1.465993046760559
Epoca: 377	Loss:1.4651403427124023
Epoca: 378	Loss:1.4642889499664307
Epoca: 379	Loss:1.463438868522644
Epoca: 380	Loss:1.4625900983810425
Epoca: 381	Loss:1.461742639541626
Epoca: 382	Loss:1.4608958959579468
Epoca: 383	Loss:1.4600510597229004
Epoca: 384	Loss:1.4592070579528809
Epoca: 385	Loss:1.458364486694336
Epoca: 386	Loss:1.4575231075286865
Epoca: 387	Loss:1.4566830396652222
Epoca: 388	Loss:1.4558441638946533
Epoca: 389	Loss:1.4550063610076904
Epoca: 390	Loss:1.4541701078414917
Epoca: 391	Loss:1.4533348083496094
Epoca: 392	Loss:1.4525009393692017
Epoca: 393	Loss:1.4516681432724
Epoca: 394	Loss:1.4508365392684937
Epoca: 395	Loss:1.4500060081481934
Epoca: 396	Loss:1.4491770267486572
Epoca: 397	Loss:1.4483489990234375
Epoca: 398	Loss:1.4475222826004028
Epoca: 399	Loss:1.4466967582702637
Epoca: 400	Loss:1.4458725452423096
Epoca: 401	Loss:1.4450494050979614
Epoca: 402	Loss:1.4442274570465088
Epoca: 403	Loss:1.4434067010879517
Epoca: 404	Loss:1.44258713722229
Epoca: 405	Loss:1.4417685270309448
Epoca: 406	Loss:1.4409514665603638
Epoca: 407	Loss:1.4401354789733887
Epoca: 408	Loss:1.4393205642700195
Epoca: 409	Loss:1.4385069608688354
Epoca: 410	Loss:1.4376944303512573
Epoca: 411	Loss:1.4368830919265747
Epoca: 412	Loss:1.436072826385498
Epoca: 413	Loss:1.435263991355896
Epoca: 414	Loss:1.4344558715820312
Epoca: 415	Loss:1.4336493015289307
Epoca: 416	Loss:1.432843804359436
Epoca: 417	Loss:1.4320393800735474
Epoca: 418	Loss:1.4312360286712646
Epoca: 419	Loss:1.4304338693618774
Epoca: 420	Loss:1.4296329021453857
Epoca: 421	Loss:1.4288331270217896
Epoca: 422	Loss:1.4280344247817993
Epoca: 423	Loss:1.427236795425415
Epoca: 424	Loss:1.4264402389526367
Epoca: 425	Loss:1.425645112991333
Epoca: 426	Loss:1.4248508214950562
Epoca: 427	Loss:1.4240577220916748
Epoca: 428	Loss:1.423265814781189
Epoca: 429	Loss:1.4224748611450195
Epoca: 430	Loss:1.4216852188110352
Epoca: 431	Loss:1.4208967685699463
Epoca: 432	Loss:1.4201091527938843
Epoca: 433	Loss:1.4193228483200073
Epoca: 434	Loss:1.4185373783111572
Epoca: 435	Loss:1.4177533388137817
Epoca: 436	Loss:1.416970133781433
Epoca: 437	Loss:1.4161882400512695
Epoca: 438	Loss:1.415407419204712
Epoca: 439	Loss:1.4146273136138916
Epoca: 440	Loss:1.413848876953125
Epoca: 441	Loss:1.4130711555480957
Epoca: 442	Loss:1.412294626235962
Epoca: 443	Loss:1.411519169807434
Epoca: 444	Loss:1.4107446670532227
Epoca: 445	Loss:1.4099713563919067
Epoca: 446	Loss:1.4091993570327759
Epoca: 447	Loss:1.4084280729293823
Epoca: 448	Loss:1.4076579809188843
Epoca: 449	Loss:1.4068889617919922
Epoca: 450	Loss:1.4061208963394165
Epoca: 451	Loss:1.4053540229797363
Epoca: 452	Loss:1.404588222503662
Epoca: 453	Loss:1.4038233757019043
Epoca: 454	Loss:1.403059720993042
Epoca: 455	Loss:1.402297019958496
Epoca: 456	Loss:1.4015352725982666
Epoca: 457	Loss:1.4007748365402222
Epoca: 458	Loss:1.4000153541564941
Epoca: 459	Loss:1.3992568254470825
Epoca: 460	Loss:1.3984992504119873
Epoca: 461	Loss:1.3977428674697876
Epoca: 462	Loss:1.3969874382019043
Epoca: 463	Loss:1.396233081817627
Epoca: 464	Loss:1.3954797983169556
Epoca: 465	Loss:1.3947277069091797
Epoca: 466	Loss:1.3939763307571411
Epoca: 467	Loss:1.3932260274887085
Epoca: 468	Loss:1.3924766778945923
Epoca: 469	Loss:1.3917285203933716
Epoca: 470	Loss:1.3909813165664673
Epoca: 471	Loss:1.390235185623169
Epoca: 472	Loss:1.3894901275634766
Epoca: 473	Loss:1.388745903968811
Epoca: 474	Loss:1.388002872467041
Epoca: 475	Loss:1.3872605562210083
Epoca: 476	Loss:1.3865195512771606
Epoca: 477	Loss:1.3857792615890503
Epoca: 478	Loss:1.385040283203125
Epoca: 479	Loss:1.3843021392822266
Epoca: 480	Loss:1.383565068244934
Epoca: 481	Loss:1.382828950881958
Epoca: 482	Loss:1.382093906402588
Epoca: 483	Loss:1.3813596963882446
Epoca: 484	Loss:1.3806266784667969
Epoca: 485	Loss:1.3798943758010864
Epoca: 486	Loss:1.3791630268096924
Epoca: 487	Loss:1.3784328699111938
Epoca: 488	Loss:1.3777035474777222
Epoca: 489	Loss:1.376975417137146
Epoca: 490	Loss:1.3762480020523071
Epoca: 491	Loss:1.3755217790603638
Epoca: 492	Loss:1.3747965097427368
Epoca: 493	Loss:1.3740719556808472
Epoca: 494	Loss:1.373348593711853
Epoca: 495	Loss:1.3726264238357544
Epoca: 496	Loss:1.3719046115875244
Epoca: 497	Loss:1.3711841106414795
Epoca: 498	Loss:1.370464563369751
Epoca: 499	Loss:1.3697459697723389
Epoca: 500	Loss:1.3690282106399536
Epoca: 501	Loss:1.3683116436004639
Epoca: 502	Loss:1.3675960302352905
Epoca: 503	Loss:1.3668811321258545
Epoca: 504	Loss:1.3661671876907349
Epoca: 505	Loss:1.3654541969299316
Epoca: 506	Loss:1.3647422790527344
Epoca: 507	Loss:1.364031434059143
Epoca: 508	Loss:1.3633211851119995
Epoca: 509	Loss:1.3626118898391724
Epoca: 510	Loss:1.3619037866592407
Epoca: 511	Loss:1.3611963987350464
Epoca: 512	Loss:1.3604899644851685
Epoca: 513	Loss:1.359784722328186
Epoca: 514	Loss:1.359080195426941
Epoca: 515	Loss:1.3583765029907227
Epoca: 516	Loss:1.3576741218566895
Epoca: 517	Loss:1.3569722175598145
Epoca: 518	Loss:1.356271505355835
Epoca: 519	Loss:1.3555713891983032
Epoca: 520	Loss:1.354872465133667
Epoca: 521	Loss:1.3541743755340576
Epoca: 522	Loss:1.3534772396087646
Epoca: 523	Loss:1.3527809381484985
Epoca: 524	Loss:1.3520857095718384
Epoca: 525	Loss:1.351391077041626
Epoca: 526	Loss:1.3506975173950195
Epoca: 527	Loss:1.350005030632019
Epoca: 528	Loss:1.3493130207061768
Epoca: 529	Loss:1.34862220287323
Epoca: 530	Loss:1.3479324579238892
Epoca: 531	Loss:1.3472434282302856
Epoca: 532	Loss:1.3465551137924194
Epoca: 533	Loss:1.3458678722381592
Epoca: 534	Loss:1.3451814651489258
Epoca: 535	Loss:1.3444960117340088
Epoca: 536	Loss:1.3438113927841187
Epoca: 537	Loss:1.3431278467178345
Epoca: 538	Loss:1.3424447774887085
Epoca: 539	Loss:1.3417627811431885
Epoca: 540	Loss:1.3410817384719849
Epoca: 541	Loss:1.340401530265808
Epoca: 542	Loss:1.3397222757339478
Epoca: 543	Loss:1.3390438556671143
Epoca: 544	Loss:1.3383662700653076
Epoca: 545	Loss:1.3376892805099487
Epoca: 546	Loss:1.3370134830474854
Epoca: 547	Loss:1.3363386392593384
Epoca: 548	Loss:1.3356643915176392
Epoca: 549	Loss:1.3349913358688354
Epoca: 550	Loss:1.33431875705719
Epoca: 551	Loss:1.3336471319198608
Epoca: 552	Loss:1.3329765796661377
Epoca: 553	Loss:1.3323066234588623
Epoca: 554	Loss:1.3316377401351929
Epoca: 555	Loss:1.3309695720672607
Epoca: 556	Loss:1.330302357673645
Epoca: 557	Loss:1.3296358585357666
Epoca: 558	Loss:1.3289703130722046
Epoca: 559	Loss:1.3283054828643799
Epoca: 560	Loss:1.3276417255401611
Epoca: 561	Loss:1.3269786834716797
Epoca: 562	Loss:1.3263163566589355
Epoca: 563	Loss:1.3256551027297974
Epoca: 564	Loss:1.324994444847107
Epoca: 565	Loss:1.3243348598480225
Epoca: 566	Loss:1.3236758708953857
Epoca: 567	Loss:1.323017954826355
Epoca: 568	Loss:1.3223607540130615
Epoca: 569	Loss:1.321704387664795
Epoca: 570	Loss:1.3210488557815552
Epoca: 571	Loss:1.3203941583633423
Epoca: 572	Loss:1.3197401762008667
Epoca: 573	Loss:1.3190871477127075
Epoca: 574	Loss:1.3184348344802856
Epoca: 575	Loss:1.3177834749221802
Epoca: 576	Loss:1.3171329498291016
Epoca: 577	Loss:1.3164831399917603
Epoca: 578	Loss:1.3158339262008667

In [78]:
vetorizador_predict = CountVectorizer(max_features=1000, vocabulary=dicionario)

In [85]:
predict_set = [
    # "the fruitwatch initiative a groundbreaking citizen science project has significantly enhanced the accuracy of predicting flowering times for fruit trees across great britain this improvement is vital for the agricultural sector enabling better planning for pest management and pollinator support which are crucial for maintaining optimal fruit yield and quality"
    # "researchers at the institute for systems biology in seattle found that bowel movement frequency could predict kidney and liver damage as well as mental health issues like depression"
    "ap entertainment writer new york ap — richard simmons television8217s hyperactive court jester of physical fitness who built a miniempire in his trademark tank tops and short shorts by urging the overweight to exercise and eat better died saturday he turned 76 on friday los angeles police and fire departments say they responded to athe post richard simmons a fitness guru who mixed laughs and sweat dies at 76 appeared first on kvia"
]

In [86]:
X_predict = vetorizador_predict.fit_transform( predict_set )
# X_predict.toarray()

In [87]:
list_reverse = ['Technology', 'Sports', 'Science', 'Health', 'General', 'Entertainment', 'Business']
with torch.no_grad():
    X_pred = torch.tensor(X_predict.toarray(), dtype=torch.float32)
    resposta = modelo( X_pred )
    indice = np.argmax( resposta )
    print(f"Este texto é sobre {list_reverse[indice]}")

Este texto é sobre Entertainment

In [65]:
# mapping = {
#         'Business': [0, 0, 0, 0, 0, 0, 1], 
#         'Entertainment': [0, 0, 0, 0, 0, 1, 0],
#         'General': [0, 0, 0, 0, 1, 0, 0],
#         'Health': [0, 0, 0, 1, 0, 0, 0], 
#         'Science': [0, 0, 1, 0, 0, 0, 0],
#         'Sports': [0, 1, 0, 0, 0, 0, 0], 
#         'Technology': [1, 0, 0, 0, 0, 0, 0]
# }
# list_reverse = ['Technology', 'Sports', 'Science', 'Health', 'General', 'Entertainment', 'Business']