In [1]:
import pandas as pd

In [16]:
import torch
import torch.nn as nn
import torch.optim as optim

In [21]:
from string import punctuation

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
df = pd.read_csv("d:/git/dados/nlp/news_sentiment_analysis.csv", encoding="utf-8")

In [7]:
df = df.drop(columns=["Source", "Author", "URL", "Published At"])

In [10]:
df

,Title,Description,Sentiment,Type
0,Pine View High teacher wins Best in State awar...,"ST. GEORGE — Kaitlyn Larson, a first-year teac...",positive,Business
1,Businesses Face Financial Strain Amid Liquidit...,"Harare, Zimbabwe – Local businesses are grappl...",neutral,Business
2,Musk donates to super pac working to elect Tru...,(marketscreener.com) Billionaire Elon Musk has...,positive,Business
3,US FTC issues warning to franchisors over unfa...,(marketscreener.com) A U.S. trade regulator on...,negative,Business
4,Rooftop solar's dark side,4.5 million households in the U.S. have solar ...,positive,Business
...,...,...,...,...
3495,"Arrow Electronics, Inc. (NYSE:ARW) Shares Purc...",QRG Capital Management Inc. increased its stak...,positive,Technology
3496,"3,120 Shares in NICE Ltd. (NASDAQ:NICE) Bought...",QRG Capital Management Inc. bought a new posit...,positive,Technology
3497,"QRG Capital Management Inc. Has $857,000 Stock...",QRG Capital Management Inc. boosted its stake ...,positive,Technology
3498,Biotechnology Market: Surging Investments and ...,"WESTFORD, Mass., July 18, 2024 /PRNewswire/ --...",neutral,Technology
3499,"QRG Capital Management Inc. Sells 1,665 Shares...",QRG Capital Management Inc. reduced its holdin...,positive,Technology

In [11]:
mapping = {"positive": 1, "negative": 0, "neutral": 0}
df["sentiment_number"] = df["Sentiment"].map( mapping )

In [12]:
df

,Title,Description,Sentiment,Type,sentiment_number
0,Pine View High teacher wins Best in State awar...,"ST. GEORGE — Kaitlyn Larson, a first-year teac...",positive,Business,1
1,Businesses Face Financial Strain Amid Liquidit...,"Harare, Zimbabwe – Local businesses are grappl...",neutral,Business,0
2,Musk donates to super pac working to elect Tru...,(marketscreener.com) Billionaire Elon Musk has...,positive,Business,1
3,US FTC issues warning to franchisors over unfa...,(marketscreener.com) A U.S. trade regulator on...,negative,Business,0
4,Rooftop solar's dark side,4.5 million households in the U.S. have solar ...,positive,Business,1
...,...,...,...,...,...
3495,"Arrow Electronics, Inc. (NYSE:ARW) Shares Purc...",QRG Capital Management Inc. increased its stak...,positive,Technology,1
3496,"3,120 Shares in NICE Ltd. (NASDAQ:NICE) Bought...",QRG Capital Management Inc. bought a new posit...,positive,Technology,1
3497,"QRG Capital Management Inc. Has $857,000 Stock...",QRG Capital Management Inc. boosted its stake ...,positive,Technology,1
3498,Biotechnology Market: Surging Investments and ...,"WESTFORD, Mass., July 18, 2024 /PRNewswire/ --...",neutral,Technology,0
3499,"QRG Capital Management Inc. Sells 1,665 Shares...",QRG Capital Management Inc. reduced its holdin...,positive,Technology,1

In [55]:
Y = torch.tensor(df["sentiment_number"], dtype=torch.float32)
Y = torch.reshape(Y, (-1, 1))

In [56]:
Y.shape

torch.Size([3500, 1])

In [22]:
table = str.maketrans("", "", punctuation)

def limpar_titulo( texto ):
    texto_limpo = texto.lower().translate(table)
    return texto_limpo

In [24]:
df["title_clean"] = df["Title"].apply(limpar_titulo)

In [87]:
df[["title_clean", "sentiment_number"]][0:10]

                                         title_clean  sentiment_number
0  pine view high teacher wins best in state awar...                 1
1  businesses face financial strain amid liquidit...                 0
2  musk donates to super pac working to elect tru...                 1
3  us ftc issues warning to franchisors over unfa...                 0
4                           rooftop solars dark side                 1
5  gabelli asks paramount for details on national...                 1
6  qwi investments  qwi ndash announcement re net...                 1
7  rome resources announces shareholder approval ...                 1
8  fawcett accused of fronting scheme for hostile...                 1
9  what makes spynn publicity the top choice for ...                 1

In [34]:
vetorizador = CountVectorizer(max_features=1000)

In [35]:
texto_vetorizado = vetorizador.fit_transform(df["title_clean"])

In [72]:
dicionario = vetorizador.get_feature_names_out()
dicionario

array(['038', '10', '100', '11', '12', '13', '14', '15', '16', '17', '18',
       '18th', '20', '2023', '2024', '202425', '2025', '2028', '2031',
       '20th', '24', '25', '26', '38', '3rd', '647th', '8th', 'about',
       'access', 'acquired', 'acquires', 'acquisition', 'across', 'act',
       'action', 'ad', 'advisers', 'advisors', 'advisory', 'afb', 'after',
       'against', 'age', 'agency', 'agreement', 'ahead', 'ai', 'aid',
       'air', 'aircraft', 'aktie', 'al', 'aldi', 'all', 'allelectric',
       'allstar', 'alto', 'amazon', 'america', 'american', 'americas',
       'amid', 'amkor', 'among', 'an', 'analysis', 'analysts',
       'analytics', 'and', 'anniversary', 'announce', 'announces',
       'annual', 'another', 'antitrans', 'ap', 'app', 'apple',
       'applications', 'appointment', 'approach', 'are', 'argentina',
       'armed', 'army', 'art', 'artillery', 'arts', 'as', 'asia', 'asks',
       'asset', 'astronaut', 'at', 'attack', 'attorney', 'attractions',
       'auf', 'august', 'australias', 'avantax', 'average', 'award',
       'awards', 'baby', 'back', 'ball', 'bancorp', 'bank', 'bc', 'be',
       'because', 'becomes', 'been', 'before', 'behind', 'bei', 'being',
       'best', 'between', 'biden', 'bielsa', 'big', 'biggest', 'bill',
       'billion', 'blackrock', 'board', 'boost', 'boss', 'bought',
       'brand', 'break', 'brigade', 'bringing', 'british', 'building',
       'burns', 'business', 'businesses', 'busy', 'but', 'buy', 'buys',
       'by', 'caesars', 'california', 'call', 'can', 'canada', 'canadian',
       'cancer', 'capital', 'care', 'cargo', 'carlos', 'case', 'cash',
       'cassava', 'caves', 'cdc', 'celebrates', 'center', 'ceo', 'chain',
       'chairman', 'change', 'changes', 'channel', 'charge', 'chase',
       'checkouts', 'chief', 'children', 'china', 'city', 'civil',
       'claims', 'class', 'close', 'closes', 'co', 'coach', 'coles',
       'collaboration', 'college', 'colorado', 'combat', 'come', 'coming',
       'commander', 'comment', 'common', 'community', 'company',
       'competition', 'completes', 'complex', 'compliance', 'con',
       'concerns', 'conducts', 'conference', 'consensus', 'consumer',
       'continue', 'contract', 'copa', 'corp', 'corporation', 'corus',
       'cosmic', 'cost', 'could', 'county', 'court', 'coverage', 'covid',
       'created', 'critical', 'cruz', 'cult', 'cup', 'customers',
       'customizable', 'cut', 'cuts', 'cvs', 'cyber', 'da', 'das', 'dash',
       'data', 'databook', 'date', 'day', 'days', 'dba', 'de', 'deal',
       'deals', 'debut', 'declares', 'decreases', 'dei', 'del', 'deliver',
       'delivers', 'dell', 'della', 'den', 'department', 'departure',
       'deputy', 'der', 'des', 'design', 'details', 'development', 'di',
       'die', 'dies', 'digital', 'director', 'directors', 'diretta',
       'disneyland', 'diverse', 'dividend', 'do', 'dog', 'dogg', 'don',
       'donald', 'donate', 'dover', 'down', 'downtown', 'dozens', 'dr',
       'draft', 'driving', 'du', 'duality', 'due', 'dunleavy', 'durable',
       'during', 'ea', 'each', 'early', 'earnings', 'ecco', 'ecigarette',
       'ecommerce', 'edition', 'education', 'effects', 'el', 'election',
       'em', 'emergency', 'empirical', 'empowered', 'en', 'end', 'energy',
       'engineer', 'england', 'enhance', 'enhances', 'entertainment',
       'erdc', 'es', 'espn', 'essential', 'este', 'etf', 'eur', 'euro',
       'euros', 'event', 'events', 'every', 'expands', 'experience',
       'experts', 'extension', 'extraordinary', 'extreme', 'fair',
       'fairchild', 'falls', 'fame', 'family', 'fans', 'fc', 'federal',
       'female', 'fest', 'field', 'fight', 'filing', 'filipino', 'film',
       'final', 'financial', 'firm', 'first', 'fiscal', 'fish', 'fitness',
       'fixedwing', 'flight', 'focus', 'following', 'follows', 'food',
       'football', 'for', 'force', 'foreign', 'form', 'former', 'fort',
       'founder', 'four', 'france', 'fraud', 'free', 'freedom', 'from',
       'full', 'funds', 'funicular', 'further', 'future', 'für',
       'galaxies', 'game', 'games', 'gaming', 'gas', 'gaza', 'gen',
       'genderaffirming', 'gene', 'general', 'generale', 'generation',
       'georgia', 'germany', 'get', 'gets', 'getting', 'gift', 'gilead',
       'gilgamesh', 'global', 'go', 'golden', 'good', 'got', 'gov',
       'government', 'grant', 'great', 'ground', 'group', 'grows',
       'growth', 'gsa', 'guide', 'h1', 'had', 'half', 'hall', 'hamas',
       'hardik', 'has', 'have', 'he', 'head', 'headlands', 'headtohead',
       'health', 'healthcare', 'hearts', 'heat', 'heatrelated', 'help',
       'her', 'here', 'hhc', 'high', 'higher', 'highlights', 'him', 'his',
       'historic', 'history', 'hold', 'holding', 'holdings', 'holistic',
       'home', 'hospital', 'hospitals', 'host', 'hosts', 'hot', 'houston',
       'how', 'hrc', 'human', 'iconic', 'if', 'il', 'illness', 'illumina',
       'im', 'image', 'in', 'inc', 'including', 'incorporated',
       'increases', 'india', 'industry', 'influencers', 'information',
       'innovation', 'inspires', 'insurance', 'integral', 'integration',
       'interest', 'international', 'into', 'investigation', 'investment',
       'investments', 'investors', 'invests', 'is', 'israeli', 'issues',
       'ist', 'it', 'italia', 'items', 'its', 'james', 'jenolan', 'jetzt',
       'joins', 'jose', 'jpmorgan', 'jr', 'judge', 'julia', 'july',
       'june', 'kardashian', 'key', 'kids', 'killed', 'kim', 'klay',
       'know', 'kpis', 'kpop', 'l3harris', 'la', 'large', 'last',
       'latest', 'launch', 'law', 'laws', 'lawsuit', 'le', 'leader',
       'leadership', 'leading', 'league', 'learn', 'legacy', 'legal',
       'les', 'lgbtq', 'liberty', 'life', 'like', 'limit', 'limited',
       'line', 'lions', 'live', 'llc', 'llp', 'local', 'long', 'los',
       'lowered', 'lowers', 'lp', 'ltd', 'lunch', 'luskins', 'made',
       'major', 'make', 'makes', 'man', 'management', 'market', 'markets',
       'massive', 'may', 'media', 'medical', 'meeting', 'melbourne',
       'melco', 'memes', 'mental', 'messi', 'midyear', 'mike', 'military',
       'million', 'minister', 'ministry', 'mit', 'mlb', 'mobile',
       'models', 'moment', 'money', 'monterey', 'moore', 'more', 'most',
       'movie', 'moving', 'murray', 'music', 'must', 'my', 'named',
       'names', 'nasdaqczr', 'nasdaqgden', 'nasdaqgild', 'nasdaqias',
       'nasdaqilmn', 'nasdaqmlco', 'nation', 'national', 'navy', 'nba',
       'nbc', 'need', 'new', 'news', 'next', 'nfl', 'nigeria', 'nintendo',
       'nmcb', 'no', 'non', 'nonotice', 'nori', 'not', 'notice', 'novel',
       'now', 'nuclear', 'nuovo', 'nyse', 'nysesaic', 'of', 'off',
       'officer', 'official', 'officials', 'oggi', 'oil', 'old',
       'olympic', 'olympics', 'on', 'one', 'only', 'open', 'opens',
       'operation', 'operational', 'oppenheimer', 'opportunities', 'or',
       'order', 'other', 'our', 'out', 'outages', 'over', 'pandya',
       'para', 'paris', 'park', 'part', 'partners', 'partnership',
       'patrioti', 'pay', 'payment', 'penn', 'people', 'per', 'pfg',
       'phone', 'photos', 'physical', 'pizza', 'place', 'plan', 'plans',
       'plant', 'play', 'players', 'plc', 'pogacar', 'police', 'por',
       'portrait', 'position', 'positive', 'potential', 'pour', 'power',
       'preparation', 'president', 'prevention', 'price', 'prime',
       'prison', 'private', 'pro', 'products', 'program', 'programs',
       'project', 'pt', 'public', 'purchased', 'purchases', 'push', 'qrg',
       'quality', 'quantbot', 'quarter', 'quarterly', 'que', 'railway',
       'raises', 'rally', 'rate', 'rating', 're', 'readiness', 'ready',
       'recall', 'receives', 'recommends', 'record', 'red', 'refill',
       'refugees', 'release', 'report', 'reports', 'research',
       'researchandmarketscom', 'resorts', 'resources', 'results',
       'return', 'revealed', 'reveals', 'revenue', 'review', 'richard',
       'right', 'rise', 'risk', 'robert', 'roivant', 'room', 'roundup',
       'rugby', 'russell', 'sa', 'safety', 'sale', 'sales', 'samsung',
       'san', 'santa', 'sapper', 'say', 'says', 'school', 'science',
       'sciences', 'scientists', 'score', 'se', 'sea', 'season', 'seat',
       'second', 'sector', 'secures', 'securities', 'security', 'see',
       'seeks', 'sees', 'sein', 'selfservice', 'sell', 'sells', 'senior',
       'sergeant', 'series', 'served', 'services', 'set', 'sg', 'share',
       'shareholder', 'shareholders', 'shares', 'she', 'shooter',
       'shooting', 'short', 'should', 'show', 'showcase', 'shows', 'sich',
       'sign', 'significant', 'signs', 'sister', 'six', 'skin',
       'skyquest', 'small', 'smart', 'smith', 'snoop', 'so', 'sold',
       'soldiers', 'solid', 'solutions', 'some', 'son', 'sources',
       'south', 'sox', 'space', 'spacelovers', 'spacex', 'spain',
       'special', 'spike', 'sport', 'sports', 'squadron', 'staff',
       'stake', 'star', 'starmer', 'stars', 'state', 'stay', 'stem',
       'stock', 'stocknewscom', 'stocks', 'storm', 'stream', 'streaming',
       'street', 'strike', 'students', 'study', 'su', 'summer', 'summit',
       'super', 'supply', 'support', 'supporting', 'supports',
       'sustainable', 'sustained', 'sweg', 'switch', 'sydney', 'system',
       'systems', 'take', 'takes', 'talk', 'talks', 'tappa', 'target',
       'taylor', 'team', 'teams', 'tech', 'technologies', 'technology',
       'temporary', 'tencent', 'tennis', 'term', 'texas', 'than', 'that',
       'the', 'their', 'there', 'they', 'things', 'this', 'thompson',
       'three', 'through', 'thursday', 'tiktok', 'time', 'tinsel',
       'title', 'to', 'tobacco', 'today', 'together', 'told', 'too',
       'top', 'tour', 'trackless', 'trade', 'trading', 'train',
       'training', 'trains', 'transformation', 'travis', 'treatment',
       'trial', 'trump', 'trust', 'trying', 'tsecjrb', 'turn', 'tutte',
       'tv', 'two', 'tyndall', 'uber', 'ubisoft', 'ucla', 'uk', 'un',
       'una', 'und', 'under', 'understanding', 'une', 'union', 'united',
       'university', 'unlocking', 'unter', 'unveils', 'up', 'update',
       'updates', 'us', 'usa', 'use', 'va', 'vannacci', 've', 'versus',
       'vet', 'video', 'visits', 'voters', 'voting', 'vs', 'wants',
       'warn', 'warns', 'warriors', 'wars', 'was', 'watch', 'water',
       'wave', 'way', 'we', 'wealth', 'wealthspire', 'week', 'welcomes',
       'west', 'what', 'when', 'where', 'white', 'who', 'why',
       'widespread', 'wie', 'wife', 'will', 'wimbledon', 'win', 'wing',
       'wins', 'wird', 'with', 'without', 'woman', 'women', 'won',
       'woolworths', 'work', 'workers', 'world', 'worth', 'wwe', 'year',
       'years', 'york', 'you', 'your', 'youth', 'zebra', 'zu'],
      dtype=object)

In [50]:
X = torch.tensor(texto_vetorizado.toarray(), dtype=torch.float32)
X

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [66]:
print("X: ", X.dtype, X.shape, X.ndim)
print("Y: ", Y.dtype, Y.shape, Y.ndim)

X:  torch.float32 torch.Size([3500, 1000]) 2
Y:  torch.float32 torch.Size([3500, 1]) 2

In [67]:
modelo = nn.Sequential(
    nn.Linear(in_features = 1000, out_features=1),
    nn.Sigmoid()
)

In [68]:
criterio = nn.BCELoss() # Binary Cross Entropy
otimizador = optim.SGD( modelo.parameters(), lr=1 )

In [70]:
for epoca in range(1, 3001):
    Y_hat = modelo( X )
    loss = criterio( Y_hat, Y )
    otimizador.zero_grad()
    loss.backward()
    otimizador.step()
    print(f"Epoca: {epoca}\tLoss:{loss}")

Epoca: 1	Loss:0.4037390351295471
Epoca: 2	Loss:0.4036838710308075
Epoca: 3	Loss:0.40362873673439026
Epoca: 4	Loss:0.4035736322402954
Epoca: 5	Loss:0.4035186469554901
Epoca: 6	Loss:0.4034636914730072
Epoca: 7	Loss:0.40340879559516907
Epoca: 8	Loss:0.4033539295196533
Epoca: 9	Loss:0.4032991826534271
Epoca: 10	Loss:0.4032445549964905
Epoca: 11	Loss:0.40318986773490906
Epoca: 12	Loss:0.4031353294849396
Epoca: 13	Loss:0.4030807614326477
Epoca: 14	Loss:0.403026282787323
Epoca: 15	Loss:0.40297189354896545
Epoca: 16	Loss:0.4029175639152527
Epoca: 17	Loss:0.4028632342815399
Epoca: 18	Loss:0.4028090536594391
Epoca: 19	Loss:0.40275490283966064
Epoca: 20	Loss:0.4027007818222046
Epoca: 21	Loss:0.4026467502117157
Epoca: 22	Loss:0.4025927782058716
Epoca: 23	Loss:0.40253889560699463
Epoca: 24	Loss:0.4024850130081177
Epoca: 25	Loss:0.4024312198162079
Epoca: 26	Loss:0.40237751603126526
Epoca: 27	Loss:0.40232381224632263
Epoca: 28	Loss:0.4022701680660248
Epoca: 29	Loss:0.4022165834903717
Epoca: 30	Loss:0.4021630883216858
Epoca: 31	Loss:0.40210965275764465
Epoca: 32	Loss:0.4020562469959259
Epoca: 33	Loss:0.4020029306411743
Epoca: 34	Loss:0.4019496440887451
Epoca: 35	Loss:0.4018964171409607
Epoca: 36	Loss:0.4018433094024658
Epoca: 37	Loss:0.40179017186164856
Epoca: 38	Loss:0.40173712372779846
Epoca: 39	Loss:0.4016841650009155
Epoca: 40	Loss:0.401631236076355
Epoca: 41	Loss:0.4015783369541168
Epoca: 42	Loss:0.4015255272388458
Epoca: 43	Loss:0.401472806930542
Epoca: 44	Loss:0.40142008662223816
Epoca: 45	Loss:0.4013674259185791
Epoca: 46	Loss:0.4013148844242096
Epoca: 47	Loss:0.4012623429298401
Epoca: 48	Loss:0.40120986104011536
Epoca: 49	Loss:0.4011574685573578
Epoca: 50	Loss:0.4011051058769226
Epoca: 51	Loss:0.4010528028011322
Epoca: 52	Loss:0.4010005593299866
Epoca: 53	Loss:0.4009483754634857
Epoca: 54	Loss:0.40089625120162964
Epoca: 55	Loss:0.40084412693977356
Epoca: 56	Loss:0.40079212188720703
Epoca: 57	Loss:0.4007401764392853
Epoca: 58	Loss:0.4006882607936859
Epoca: 59	Loss:0.40063637495040894
Epoca: 60	Loss:0.4005846083164215
Epoca: 61	Loss:0.4005328416824341
Epoca: 62	Loss:0.4004811644554138
Epoca: 63	Loss:0.40042951703071594
Epoca: 64	Loss:0.40037795901298523
Epoca: 65	Loss:0.4003264605998993
Epoca: 66	Loss:0.40027496218681335
Epoca: 67	Loss:0.40022361278533936
Epoca: 68	Loss:0.4001722037792206
Epoca: 69	Loss:0.40012088418006897
Epoca: 70	Loss:0.4000696539878845
Epoca: 71	Loss:0.4000183939933777
Epoca: 72	Loss:0.3999672830104828
Epoca: 73	Loss:0.39991623163223267
Epoca: 74	Loss:0.39986515045166016
Epoca: 75	Loss:0.3998141884803772
Epoca: 76	Loss:0.399763286113739
Epoca: 77	Loss:0.39971235394477844
Epoca: 78	Loss:0.3996615409851074
Epoca: 79	Loss:0.39961081743240356
Epoca: 80	Loss:0.3995600938796997
Epoca: 81	Loss:0.399509459733963
Epoca: 82	Loss:0.3994588553905487
Epoca: 83	Loss:0.3994082510471344
Epoca: 84	Loss:0.39935776591300964
Epoca: 85	Loss:0.3993073105812073
Epoca: 86	Loss:0.3992569148540497
Epoca: 87	Loss:0.3992065489292145
Epoca: 88	Loss:0.39915624260902405
Epoca: 89	Loss:0.3991060256958008
Epoca: 90	Loss:0.3990558087825775
Epoca: 91	Loss:0.3990057110786438
Epoca: 92	Loss:0.3989556133747101
Epoca: 93	Loss:0.39890554547309875
Epoca: 94	Loss:0.398855596780777
Epoca: 95	Loss:0.3988056182861328
Epoca: 96	Loss:0.3987557590007782
Epoca: 97	Loss:0.39870595932006836
Epoca: 98	Loss:0.3986561894416809
Epoca: 99	Loss:0.39860644936561584
Epoca: 100	Loss:0.39855676889419556
Epoca: 101	Loss:0.39850717782974243
Epoca: 102	Loss:0.3984575569629669
Epoca: 103	Loss:0.39840805530548096
Epoca: 104	Loss:0.3983585834503174
Epoca: 105	Loss:0.3983091413974762
Epoca: 106	Loss:0.3982597887516022
Epoca: 107	Loss:0.39821043610572815
Epoca: 108	Loss:0.3981611728668213
Epoca: 109	Loss:0.398112028837204
Epoca: 110	Loss:0.3980628550052643
Epoca: 111	Loss:0.39801374077796936
Epoca: 112	Loss:0.39796459674835205
Epoca: 113	Loss:0.39791563153266907
Epoca: 114	Loss:0.3978666663169861
Epoca: 115	Loss:0.39781779050827026
Epoca: 116	Loss:0.39776891469955444
Epoca: 117	Loss:0.397720068693161
Epoca: 118	Loss:0.39767125248908997
Epoca: 119	Loss:0.39762255549430847
Epoca: 120	Loss:0.39757391810417175
Epoca: 121	Loss:0.39752528071403503
Epoca: 122	Loss:0.3974767029285431
Epoca: 123	Loss:0.39742815494537354
Epoca: 124	Loss:0.3973797559738159
Epoca: 125	Loss:0.39733123779296875
Epoca: 126	Loss:0.3972828984260559
Epoca: 127	Loss:0.39723455905914307
Epoca: 128	Loss:0.397186279296875
Epoca: 129	Loss:0.3971380889415741
Epoca: 130	Loss:0.3970898687839508
Epoca: 131	Loss:0.3970417082309723
Epoca: 132	Loss:0.3969936966896057
Epoca: 133	Loss:0.39694565534591675
Epoca: 134	Loss:0.39689764380455017
Epoca: 135	Loss:0.39684969186782837
Epoca: 136	Loss:0.39680179953575134
Epoca: 137	Loss:0.3967539072036743
Epoca: 138	Loss:0.39670610427856445
Epoca: 139	Loss:0.39665839076042175
Epoca: 140	Loss:0.39661070704460144
Epoca: 141	Loss:0.39656302332878113
Epoca: 142	Loss:0.396515429019928
Epoca: 143	Loss:0.39646783471107483
Epoca: 144	Loss:0.39642032980918884
Epoca: 145	Loss:0.39637288451194763
Epoca: 146	Loss:0.3963254690170288
Epoca: 147	Loss:0.3962780833244324
Epoca: 148	Loss:0.3962307572364807
Epoca: 149	Loss:0.39618349075317383
Epoca: 150	Loss:0.3961363136768341
Epoca: 151	Loss:0.3960890769958496
Epoca: 152	Loss:0.3960419297218323
Epoca: 153	Loss:0.39599478244781494
Epoca: 154	Loss:0.39594778418540955
Epoca: 155	Loss:0.3959007263183594
Epoca: 156	Loss:0.39585378766059875
Epoca: 157	Loss:0.3958068788051605
Epoca: 158	Loss:0.3957599997520447
Epoca: 159	Loss:0.3957131803035736
Epoca: 160	Loss:0.3956664204597473
Epoca: 161	Loss:0.3956196904182434
Epoca: 162	Loss:0.3955730199813843
Epoca: 163	Loss:0.39552631974220276
Epoca: 164	Loss:0.3954797387123108
Epoca: 165	Loss:0.395433247089386
Epoca: 166	Loss:0.3953867256641388
Epoca: 167	Loss:0.39534029364585876
Epoca: 168	Loss:0.39529386162757874
Epoca: 169	Loss:0.39524751901626587
Epoca: 170	Loss:0.3952011466026306
Epoca: 171	Loss:0.3951549232006073
Epoca: 172	Loss:0.3951086699962616
Epoca: 173	Loss:0.39506247639656067
Epoca: 174	Loss:0.39501631259918213
Epoca: 175	Loss:0.39497023820877075
Epoca: 176	Loss:0.3949241638183594
Epoca: 177	Loss:0.39487820863723755
Epoca: 178	Loss:0.39483219385147095
Epoca: 179	Loss:0.3947862684726715
Epoca: 180	Loss:0.39474043250083923
Epoca: 181	Loss:0.3946945369243622
Epoca: 182	Loss:0.39464882016181946
Epoca: 183	Loss:0.39460301399230957
Epoca: 184	Loss:0.39455732703208923
Epoca: 185	Loss:0.3945116698741913
Epoca: 186	Loss:0.3944661319255829
Epoca: 187	Loss:0.3944205641746521
Epoca: 188	Loss:0.3943749964237213
Epoca: 189	Loss:0.3943295180797577
Epoca: 190	Loss:0.39428406953811646
Epoca: 191	Loss:0.3942386507987976
Epoca: 192	Loss:0.3941933214664459
Epoca: 193	Loss:0.394148051738739
Epoca: 194	Loss:0.3941027522087097
Epoca: 195	Loss:0.3940575122833252
Epoca: 196	Loss:0.39401233196258545
Epoca: 197	Loss:0.3939672112464905
Epoca: 198	Loss:0.3939221203327179
Epoca: 199	Loss:0.3938770592212677
Epoca: 200	Loss:0.3938320279121399
Epoca: 201	Loss:0.39378711581230164
Epoca: 202	Loss:0.393742173910141
Epoca: 203	Loss:0.3936972916126251
Epoca: 204	Loss:0.39365246891975403
Epoca: 205	Loss:0.3936076760292053
Epoca: 206	Loss:0.3935628831386566
Epoca: 207	Loss:0.39351820945739746
Epoca: 208	Loss:0.3934735059738159
Epoca: 209	Loss:0.39342889189720154
Epoca: 210	Loss:0.39338427782058716
Epoca: 211	Loss:0.39333978295326233
Epoca: 212	Loss:0.3932952284812927
Epoca: 213	Loss:0.39325079321861267
Epoca: 214	Loss:0.39320632815361023
Epoca: 215	Loss:0.3931620121002197
Epoca: 216	Loss:0.39311766624450684
Epoca: 217	Loss:0.3930733799934387
Epoca: 218	Loss:0.3930290639400482
Epoca: 219	Loss:0.39298486709594727
Epoca: 220	Loss:0.3929407000541687
Epoca: 221	Loss:0.3928965926170349
Epoca: 222	Loss:0.39285245537757874
Epoca: 223	Loss:0.3928084075450897
Epoca: 224	Loss:0.3927643895149231
Epoca: 225	Loss:0.39272043108940125
Epoca: 226	Loss:0.39267656207084656
Epoca: 227	Loss:0.3926326334476471
Epoca: 228	Loss:0.3925887942314148
Epoca: 229	Loss:0.3925449848175049
Epoca: 230	Loss:0.39250126481056213
Epoca: 231	Loss:0.3924574851989746
Epoca: 232	Loss:0.39241382479667664
Epoca: 233	Loss:0.39237019419670105
Epoca: 234	Loss:0.39232659339904785
Epoca: 235	Loss:0.39228299260139465
Epoca: 236	Loss:0.39223942160606384
Epoca: 237	Loss:0.3921959698200226
Epoca: 238	Loss:0.3921525478363037
Epoca: 239	Loss:0.3921091556549072
Epoca: 240	Loss:0.39206573367118835
Epoca: 241	Loss:0.3920224905014038
Epoca: 242	Loss:0.3919791579246521
Epoca: 243	Loss:0.39193588495254517
Epoca: 244	Loss:0.3918927311897278
Epoca: 245	Loss:0.391849547624588
Epoca: 246	Loss:0.391806423664093
Epoca: 247	Loss:0.3917633295059204
Epoca: 248	Loss:0.3917202353477478
Epoca: 249	Loss:0.39167729020118713
Epoca: 250	Loss:0.3916343152523041
Epoca: 251	Loss:0.3915913701057434
Epoca: 252	Loss:0.3915484547615051
Epoca: 253	Loss:0.39150556921958923
Epoca: 254	Loss:0.3914628326892853
Epoca: 255	Loss:0.3914199769496918
Epoca: 256	Loss:0.3913773000240326
Epoca: 257	Loss:0.3913346230983734
Epoca: 258	Loss:0.39129188656806946
Epoca: 259	Loss:0.39124932885169983
Epoca: 260	Loss:0.3912067413330078
Epoca: 261	Loss:0.39116421341896057
Epoca: 262	Loss:0.39112165570259094
Epoca: 263	Loss:0.39107924699783325
Epoca: 264	Loss:0.39103683829307556
Epoca: 265	Loss:0.3909943699836731
Epoca: 266	Loss:0.3909520208835602
Epoca: 267	Loss:0.39090973138809204
Epoca: 268	Loss:0.3908674716949463
Epoca: 269	Loss:0.3908252418041229
Epoca: 270	Loss:0.39078304171562195
Epoca: 271	Loss:0.39074084162712097
Epoca: 272	Loss:0.39069870114326477
Epoca: 273	Loss:0.39065659046173096
Epoca: 274	Loss:0.3906145691871643
Epoca: 275	Loss:0.39057257771492004
Epoca: 276	Loss:0.3905305564403534
Epoca: 277	Loss:0.3904886543750763
Epoca: 278	Loss:0.3904467523097992
Epoca: 279	Loss:0.3904048502445221
Epoca: 280	Loss:0.39036303758621216
Epoca: 281	Loss:0.3903212547302246
Epoca: 282	Loss:0.39027950167655945
Epoca: 283	Loss:0.3902377784252167
Epoca: 284	Loss:0.3901961147785187
Epoca: 285	Loss:0.39015451073646545
Epoca: 286	Loss:0.39011287689208984
Epoca: 287	Loss:0.390071302652359
Epoca: 288	Loss:0.39002978801727295
Epoca: 289	Loss:0.3899882733821869
Epoca: 290	Loss:0.3899467885494232
Epoca: 291	Loss:0.38990533351898193
Epoca: 292	Loss:0.3898640275001526
Epoca: 293	Loss:0.38982266187667847
Epoca: 294	Loss:0.38978132605552673
Epoca: 295	Loss:0.3897400498390198
Epoca: 296	Loss:0.3896988332271576
Epoca: 297	Loss:0.389657586812973
Epoca: 298	Loss:0.3896164298057556
Epoca: 299	Loss:0.3895753026008606
Epoca: 300	Loss:0.38953420519828796
Epoca: 301	Loss:0.3894931674003601
Epoca: 302	Loss:0.38945209980010986
Epoca: 303	Loss:0.3894111216068268
Epoca: 304	Loss:0.3893701732158661
Epoca: 305	Loss:0.38932928442955017
Epoca: 306	Loss:0.38928839564323425
Epoca: 307	Loss:0.3892475664615631
Epoca: 308	Loss:0.38920676708221436
Epoca: 309	Loss:0.3891659379005432
Epoca: 310	Loss:0.38912519812583923
Epoca: 311	Loss:0.38908451795578003
Epoca: 312	Loss:0.3890438377857208
Epoca: 313	Loss:0.3890032172203064
Epoca: 314	Loss:0.3889625668525696
Epoca: 315	Loss:0.3889220356941223
Epoca: 316	Loss:0.38888153433799744
Epoca: 317	Loss:0.38884103298187256
Epoca: 318	Loss:0.3888005316257477
Epoca: 319	Loss:0.38876014947891235
Epoca: 320	Loss:0.38871973752975464
Epoca: 321	Loss:0.3886794149875641
Epoca: 322	Loss:0.38863909244537354
Epoca: 323	Loss:0.388598769903183
Epoca: 324	Loss:0.388558566570282
Epoca: 325	Loss:0.3885183334350586
Epoca: 326	Loss:0.3884781301021576
Epoca: 327	Loss:0.38843798637390137
Epoca: 328	Loss:0.38839787244796753
Epoca: 329	Loss:0.3883577585220337
Epoca: 330	Loss:0.3883177638053894
Epoca: 331	Loss:0.38827773928642273
Epoca: 332	Loss:0.3882378041744232
Epoca: 333	Loss:0.3881978690624237
Epoca: 334	Loss:0.3881579339504242
Epoca: 335	Loss:0.38811805844306946
Epoca: 336	Loss:0.3880782425403595
Epoca: 337	Loss:0.38803842663764954
Epoca: 338	Loss:0.38799864053726196
Epoca: 339	Loss:0.38795891404151917
Epoca: 340	Loss:0.38791921734809875
Epoca: 341	Loss:0.38787952065467834
Epoca: 342	Loss:0.3878399133682251
Epoca: 343	Loss:0.38780030608177185
Epoca: 344	Loss:0.387760728597641
Epoca: 345	Loss:0.3877211809158325
Epoca: 346	Loss:0.3876817226409912
Epoca: 347	Loss:0.3876422345638275
Epoca: 348	Loss:0.3876027762889862
Epoca: 349	Loss:0.38756340742111206
Epoca: 350	Loss:0.3875240683555603
Epoca: 351	Loss:0.38748469948768616
Epoca: 352	Loss:0.3874453902244568
Epoca: 353	Loss:0.3874061107635498
Epoca: 354	Loss:0.38736692070961
Epoca: 355	Loss:0.3873277008533478
Epoca: 356	Loss:0.38728851079940796
Epoca: 357	Loss:0.3872493803501129
Epoca: 358	Loss:0.38721027970314026
Epoca: 359	Loss:0.38717120885849
Epoca: 360	Loss:0.3871321380138397
Epoca: 361	Loss:0.3870931565761566
Epoca: 362	Loss:0.3870542049407959
Epoca: 363	Loss:0.38701528310775757
Epoca: 364	Loss:0.38697636127471924
Epoca: 365	Loss:0.3869374990463257
Epoca: 366	Loss:0.38689860701560974
Epoca: 367	Loss:0.38685980439186096
Epoca: 368	Loss:0.38682103157043457
Epoca: 369	Loss:0.38678228855133057
Epoca: 370	Loss:0.38674357533454895
Epoca: 371	Loss:0.3867048919200897
Epoca: 372	Loss:0.38666626811027527
Epoca: 373	Loss:0.3866276144981384
Epoca: 374	Loss:0.38658902049064636
Epoca: 375	Loss:0.3865504562854767
Epoca: 376	Loss:0.38651201128959656
Epoca: 377	Loss:0.38647350668907166
Epoca: 378	Loss:0.38643503189086914
Epoca: 379	Loss:0.386396586894989
Epoca: 380	Loss:0.38635820150375366
Epoca: 381	Loss:0.3863198459148407
Epoca: 382	Loss:0.3862815201282501
Epoca: 383	Loss:0.38624319434165955
Epoca: 384	Loss:0.38620489835739136
Epoca: 385	Loss:0.3861667513847351
Epoca: 386	Loss:0.3861284852027893
Epoca: 387	Loss:0.38609033823013306
Epoca: 388	Loss:0.3860521614551544
Epoca: 389	Loss:0.38601404428482056
Epoca: 390	Loss:0.38597601652145386
Epoca: 391	Loss:0.38593795895576477
Epoca: 392	Loss:0.38589993119239807
Epoca: 393	Loss:0.38586193323135376
Epoca: 394	Loss:0.38582393527030945
Epoca: 395	Loss:0.3857860565185547
Epoca: 396	Loss:0.38574814796447754
Epoca: 397	Loss:0.3857102692127228
Epoca: 398	Loss:0.3856724798679352
Epoca: 399	Loss:0.3856346905231476
Epoca: 400	Loss:0.38559690117836
Epoca: 401	Loss:0.3855591416358948
Epoca: 402	Loss:0.38552147150039673
Epoca: 403	Loss:0.3854837715625763
Epoca: 404	Loss:0.38544610142707825
Epoca: 405	Loss:0.385408490896225
Epoca: 406	Loss:0.3853708803653717
Epoca: 407	Loss:0.385333389043808
Epoca: 408	Loss:0.3852958381175995
Epoca: 409	Loss:0.38525834679603577
Epoca: 410	Loss:0.38522085547447205
Epoca: 411	Loss:0.3851834535598755
Epoca: 412	Loss:0.38514605164527893
Epoca: 413	Loss:0.38510867953300476
Epoca: 414	Loss:0.38507136702537537
Epoca: 415	Loss:0.3850339949131012
Epoca: 416	Loss:0.3849967122077942
Epoca: 417	Loss:0.38495945930480957
Epoca: 418	Loss:0.3849222958087921
Epoca: 419	Loss:0.3848850727081299
Epoca: 420	Loss:0.3848479390144348
Epoca: 421	Loss:0.38481080532073975
Epoca: 422	Loss:0.3847736716270447
Epoca: 423	Loss:0.3847365975379944
Epoca: 424	Loss:0.3846994936466217
Epoca: 425	Loss:0.38466253876686096
Epoca: 426	Loss:0.38462552428245544
Epoca: 427	Loss:0.3845885992050171
Epoca: 428	Loss:0.38455167412757874
Epoca: 429	Loss:0.38451480865478516
Epoca: 430	Loss:0.3844779133796692
Epoca: 431	Loss:0.384441077709198
Epoca: 432	Loss:0.3844042718410492
Epoca: 433	Loss:0.3843674957752228
Epoca: 434	Loss:0.38433074951171875
Epoca: 435	Loss:0.3842940032482147
Epoca: 436	Loss:0.38425731658935547
Epoca: 437	Loss:0.3842206597328186
Epoca: 438	Loss:0.3841840326786041
Epoca: 439	Loss:0.38414743542671204
Epoca: 440	Loss:0.38411086797714233
Epoca: 441	Loss:0.38407430052757263
Epoca: 442	Loss:0.3840377926826477
Epoca: 443	Loss:0.3840012848377228
Epoca: 444	Loss:0.383964866399765
Epoca: 445	Loss:0.3839283883571625
Epoca: 446	Loss:0.3838920295238495
Epoca: 447	Loss:0.3838556408882141
Epoca: 448	Loss:0.38381925225257874
Epoca: 449	Loss:0.3837829828262329
Epoca: 450	Loss:0.3837467133998871
Epoca: 451	Loss:0.38371044397354126
Epoca: 452	Loss:0.3836742043495178
Epoca: 453	Loss:0.3836379647254944
Epoca: 454	Loss:0.3836018443107605
Epoca: 455	Loss:0.38356566429138184
Epoca: 456	Loss:0.38352957367897034
Epoca: 457	Loss:0.38349348306655884
Epoca: 458	Loss:0.3834574520587921
Epoca: 459	Loss:0.383421391248703
Epoca: 460	Loss:0.38338539004325867
Epoca: 461	Loss:0.38334938883781433
Epoca: 462	Loss:0.38331347703933716
Epoca: 463	Loss:0.38327756524086
Epoca: 464	Loss:0.3832416534423828
Epoca: 465	Loss:0.3832058012485504
Epoca: 466	Loss:0.383169949054718
Epoca: 467	Loss:0.3831341862678528
Epoca: 468	Loss:0.38309839367866516
Epoca: 469	Loss:0.3830626308917999
Epoca: 470	Loss:0.3830268979072571
Epoca: 471	Loss:0.3829912543296814
Epoca: 472	Loss:0.3829555809497833
Epoca: 473	Loss:0.38291990756988525
Epoca: 474	Loss:0.38288432359695435
Epoca: 475	Loss:0.38284873962402344
Epoca: 476	Loss:0.38281315565109253
Epoca: 477	Loss:0.3827776312828064
Epoca: 478	Loss:0.38274210691452026
Epoca: 479	Loss:0.3827066421508789
Epoca: 480	Loss:0.38267120718955994
Epoca: 481	Loss:0.38263580203056335
Epoca: 482	Loss:0.3826003670692444
Epoca: 483	Loss:0.3825650215148926
Epoca: 484	Loss:0.38252967596054077
Epoca: 485	Loss:0.38249436020851135
Epoca: 486	Loss:0.3824591338634491
Epoca: 487	Loss:0.3824238181114197
Epoca: 488	Loss:0.3823885917663574
Epoca: 489	Loss:0.38235342502593994
Epoca: 490	Loss:0.3823182284832001
Epoca: 491	Loss:0.3822830319404602
Epoca: 492	Loss:0.3822479844093323
Epoca: 493	Loss:0.3822128474712372
Epoca: 494	Loss:0.38217779994010925
Epoca: 495	Loss:0.3821427524089813
Epoca: 496	Loss:0.3821077346801758
Epoca: 497	Loss:0.3820727467536926
Epoca: 498	Loss:0.38203781843185425
Epoca: 499	Loss:0.3820028603076935
Epoca: 500	Loss:0.3819679021835327
Epoca: 501	Loss:0.3819330334663391
Epoca: 502	Loss:0.3818982243537903
Epoca: 503	Loss:0.38186338543891907
Epoca: 504	Loss:0.38182854652404785
Epoca: 505	Loss:0.3817937970161438
Epoca: 506	Loss:0.38175907731056213
Epoca: 507	Loss:0.38172435760498047
Epoca: 508	Loss:0.3816896378993988
Epoca: 509	Loss:0.3816549479961395
Epoca: 510	Loss:0.381620317697525
Epoca: 511	Loss:0.3815856873989105
Epoca: 512	Loss:0.3815510869026184
Epoca: 513	Loss:0.38151654601097107
Epoca: 514	Loss:0.38148197531700134
Epoca: 515	Loss:0.3814474642276764
Epoca: 516	Loss:0.3814130127429962
Epoca: 517	Loss:0.38137856125831604
Epoca: 518	Loss:0.38134410977363586
Epoca: 519	Loss:0.38130971789360046
Epoca: 520	Loss:0.38127532601356506
Epoca: 521	Loss:0.38124096393585205
Epoca: 522	Loss:0.38120660185813904
Epoca: 523	Loss:0.3811723291873932
Epoca: 524	Loss:0.38113799691200256
Epoca: 525	Loss:0.3811037838459015
Epoca: 526	Loss:0.3810695707798004
Epoca: 527	Loss:0.38103535771369934
Epoca: 528	Loss:0.38100117444992065
Epoca: 529	Loss:0.38096705079078674
Epoca: 530	Loss:0.38093289732933044
Epoca: 531	Loss:0.3808988332748413
Epoca: 532	Loss:0.3808647096157074
Epoca: 533	Loss:0.38083070516586304
Epoca: 534	Loss:0.3807966709136963
Epoca: 535	Loss:0.3807626962661743
Epoca: 536	Loss:0.38072869181632996
Epoca: 537	Loss:0.38069474697113037
Epoca: 538	Loss:0.3806608319282532
Epoca: 539	Loss:0.38062694668769836
Epoca: 540	Loss:0.38059306144714355
Epoca: 541	Loss:0.38055917620658875
Epoca: 542	Loss:0.3805253803730011
Epoca: 543	Loss:0.38049158453941345
Epoca: 544	Loss:0.3804577887058258
Epoca: 545	Loss:0.38042402267456055
Epoca: 546	Loss:0.38039037585258484
Epoca: 547	Loss:0.38035666942596436
Epoca: 548	Loss:0.38032296299934387
Epoca: 549	Loss:0.38028934597969055
Epoca: 550	Loss:0.3802557587623596
Epoca: 551	Loss:0.3802221119403839
Epoca: 552	Loss:0.380188524723053
Epoca: 553	Loss:0.3801549971103668
Epoca: 554	Loss:0.38012146949768066
Epoca: 555	Loss:0.3800879716873169
Epoca: 556	Loss:0.3800545036792755
Epoca: 557	Loss:0.3800210654735565
Epoca: 558	Loss:0.37998759746551514
Epoca: 559	Loss:0.3799542188644409
Epoca: 560	Loss:0.3799208700656891
Epoca: 561	Loss:0.37988752126693726
Epoca: 562	Loss:0.37985414266586304
Epoca: 563	Loss:0.37982088327407837
Epoca: 564	Loss:0.3797875940799713
Epoca: 565	Loss:0.37975427508354187
Epoca: 566	Loss:0.379721075296402
Epoca: 567	Loss:0.3796879053115845
Epoca: 568	Loss:0.3796547055244446

In [73]:
vetorizador_predict = CountVectorizer(max_features=1000, vocabulary=dicionario)

In [84]:
X_predict = vetorizador_predict.fit_transform( df["title_clean"][0:10] )
X_predict.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(10, 1000))

In [86]:
with torch.no_grad():
    X_pred = torch.tensor(X_predict.toarray(), dtype=torch.float32)
    resposta = modelo( X_pred )
    print(f"Resposta: {resposta}")

Resposta: tensor([[0.9879],
        [0.3327],
        [0.8803],
        [0.6030],
        [0.6939],
        [0.8062],
        [0.3120],
        [0.7129],
        [0.7087],
        [0.8809]])